"""add_indexes_to_cars_table

Revision ID: 28f544bafddd
Revises: d049065b730f
Create Date: 2026-01-07 22:49:06.830352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f544bafddd'
down_revision: Union[str, Sequence[str], None] = 'd049065b730f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Functional indexes for case-insensitive text search
    op.create_index(
        'idx_cars_make_lower',
        'cars',
        [sa.text('LOWER(make)')],
        unique=False,
    )

    op.create_index(
        'idx_cars_model_lower',
        'cars',
        [sa.text('LOWER(model)')],
        unique=False,
    )

    # B-tree indexes for range queries
    op.create_index(
        'idx_cars_year',
        'cars',
        ['year'],
        unique=False,
    )

    op.create_index(
        'idx_cars_price',
        'cars',
        ['price'],
        unique=False,
    )

    # Composite index for common filter combination
    op.create_index(
        'idx_cars_make_lower_price',
        'cars',
        [sa.text('LOWER(make)'), 'price'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cars_make_lower_price', table_name='cars')
    op.drop_index('idx_cars_price', table_name='cars')
    op.drop_index('idx_cars_year', table_name='cars')
    op.drop_index('idx_cars_model_lower', table_name='cars')
    op.drop_index('idx_cars_make_lower', table_name='cars')
    # ### end Alembic commands ###
